import { Command, type Option } from "commander";

export interface CompletionNode {
  name: string;
  description: string;
  aliases: string[];
  flags: string[];
  subcommands: CompletionNode[];
}

export type Shell = "bash" | "zsh" | "fish";

export function buildCompletionTree(program: Command): CompletionNode {
  return walk(program);
}

function walk(cmd: Command): CompletionNode {
  const subs = (cmd.commands ?? []).filter((c) => c.name() !== "help");
  return {
    name: cmd.name(),
    description: cmd.description() ?? "",
    aliases: cmd.aliases(),
    flags: collectFlags(cmd),
    subcommands: subs.map((s) => walk(s)),
  };
}

function collectFlags(cmd: Command): string[] {
  const flags: string[] = [];
  for (const opt of cmd.options) {
    flags.push(...flagsFromOption(opt));
  }
  flags.push("--help", "-h");
  return Array.from(new Set(flags));
}

function flagsFromOption(opt: Option): string[] {
  // `opt.flags` looks like "-V, --version" or "--name <id>".
  const out: string[] = [];
  for (const piece of opt.flags.split(/[,\s]+/)) {
    if (piece.startsWith("-")) out.push(piece);
  }
  return out;
}

export function renderCompletion(tree: CompletionNode, shell: Shell): string {
  if (shell === "bash") return renderBash(tree);
  if (shell === "zsh") return renderZsh(tree);
  return renderFish(tree);
}

// --- bash ---

function renderBash(tree: CompletionNode): string {
  const cmdNames = tree.subcommands.map((s) => s.name);
  const aliases = tree.subcommands.flatMap((s) => s.aliases);
  const topWords = [...cmdNames, ...aliases].join(" ");

  const subcaseArms = tree.subcommands.map((sub) => bashSubArm(sub)).join("\n");

  return `# bash completion for foreman — generated by 'foreman completion bash'
# Source this file or drop it into /etc/bash_completion.d/foreman

_foreman_complete() {
  local cur prev words cword
  cur="\${COMP_WORDS[COMP_CWORD]}"

  if [ "\${COMP_CWORD}" -eq 1 ]; then
    COMPREPLY=( $(compgen -W "${topWords} --help --version" -- "\${cur}") )
    return 0
  fi

  local sub="\${COMP_WORDS[1]}"
  case "\${sub}" in
${subcaseArms}
    *)
      COMPREPLY=()
      ;;
  esac
}

complete -F _foreman_complete foreman
`;
}

function bashSubArm(sub: CompletionNode): string {
  const nestedNames = sub.subcommands.map((n) => n.name).join(" ");
  const flags = sub.flags.join(" ");
  if (sub.subcommands.length === 0) {
    return `    ${sub.name})
      COMPREPLY=( $(compgen -W "${flags}" -- "\${cur}") )
      ;;`;
  }
  return `    ${sub.name})
      if [ "\${COMP_CWORD}" -eq 2 ]; then
        COMPREPLY=( $(compgen -W "${nestedNames} ${flags}" -- "\${cur}") )
      else
        COMPREPLY=( $(compgen -W "${flags}" -- "\${cur}") )
      fi
      ;;`;
}

// --- zsh ---

function renderZsh(tree: CompletionNode): string {
  const lines: string[] = [];
  lines.push(`#compdef foreman`);
  lines.push(``);
  lines.push(
    `# zsh completion for foreman — generated by 'foreman completion zsh'`,
  );
  lines.push(`# Drop this file at "\${fpath[1]}/_foreman" then 'compinit -u'`);
  lines.push(``);
  lines.push(`_foreman() {`);
  lines.push(`  local context state line`);
  lines.push(`  _arguments -C \\`);
  lines.push(`    '1: :->cmd' \\`);
  lines.push(`    '*::arg:->args'`);
  lines.push(``);
  lines.push(`  case \$state in`);
  lines.push(`    cmd)`);
  lines.push(`      local -a commands`);
  lines.push(`      commands=(`);
  for (const sub of tree.subcommands) {
    lines.push(`        '${sub.name}:${escapeZsh(sub.description)}'`);
  }
  lines.push(`      )`);
  lines.push(`      _describe -t commands 'foreman commands' commands`);
  lines.push(`      ;;`);
  lines.push(`    args)`);
  lines.push(`      case \$line[1] in`);
  for (const sub of tree.subcommands) {
    lines.push(...zshSubcommandArms(sub));
  }
  lines.push(`      esac`);
  lines.push(`      ;;`);
  lines.push(`  esac`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`_foreman "$@"`);
  return lines.join("\n") + "\n";
}

function zshSubcommandArms(sub: CompletionNode): string[] {
  const lines: string[] = [];
  lines.push(`        ${sub.name})`);
  if (sub.subcommands.length === 0) {
    const flags = sub.flags
      .map((f) => `            '${f}[option]'`)
      .join(" \\\n");
    if (flags.length > 0) {
      lines.push(`          _arguments \\\n${flags}`);
    } else {
      lines.push(`          _message 'no further completion'`);
    }
  } else {
    lines.push(`          local -a subs`);
    lines.push(`          subs=(`);
    for (const nested of sub.subcommands) {
      lines.push(
        `            '${nested.name}:${escapeZsh(nested.description)}'`,
      );
    }
    lines.push(`          )`);
    lines.push(
      `          _describe -t subcommands '${sub.name} subcommands' subs`,
    );
  }
  lines.push(`          ;;`);
  return lines;
}

function escapeZsh(s: string): string {
  return s.replace(/'/g, "''");
}

// --- fish ---

function renderFish(tree: CompletionNode): string {
  const lines: string[] = [];
  lines.push(
    `# fish completion for foreman — generated by 'foreman completion fish'`,
  );
  lines.push(`# Drop this file at ~/.config/fish/completions/foreman.fish`);
  lines.push(``);
  lines.push(`function __foreman_no_subcommand`);
  lines.push(`  for cmd in (commandline -opc)`);
  lines.push(
    `    if contains -- \$cmd ${tree.subcommands.map((s) => s.name).join(" ")}`,
  );
  lines.push(`      return 1`);
  lines.push(`    end`);
  lines.push(`  end`);
  lines.push(`  return 0`);
  lines.push(`end`);
  lines.push(``);
  for (const sub of tree.subcommands) {
    lines.push(
      `complete -c foreman -n '__foreman_no_subcommand' -a '${sub.name}' -d '${escapeFish(sub.description)}'`,
    );
  }
  for (const sub of tree.subcommands) {
    for (const flag of sub.flags) {
      const cleaned = flag.replace(/^-+/, "");
      const isLong = flag.startsWith("--");
      lines.push(
        `complete -c foreman -n '__fish_seen_subcommand_from ${sub.name}' ${
          isLong ? "-l" : "-s"
        } '${cleaned}'`,
      );
    }
    for (const nested of sub.subcommands) {
      lines.push(
        `complete -c foreman -n '__fish_seen_subcommand_from ${sub.name}; and not __fish_seen_subcommand_from ${tree.subcommands
          .filter((s) => s.name !== sub.name)
          .map((s) => s.name)
          .join(
            " ",
          )}' -a '${nested.name}' -d '${escapeFish(nested.description)}'`,
      );
    }
  }
  return lines.join("\n") + "\n";
}

function escapeFish(s: string): string {
  return s.replace(/'/g, "\\'");
}

export function createCompletionCommand(getProgram: () => Command): Command {
  return new Command("completion")
    .description("Print a shell completion script (bash, zsh, fish)")
    .argument("<shell>", "Target shell — bash, zsh, or fish")
    .action((shell: string) => {
      if (shell !== "bash" && shell !== "zsh" && shell !== "fish") {
        process.stderr.write(
          `error: unsupported shell "${shell}". Pick one of bash, zsh, fish.\n`,
        );
        process.exit(1);
      }
      const tree = buildCompletionTree(getProgram());
      process.stdout.write(renderCompletion(tree, shell));
    });
}
